doctrine:
  dbal:
    url: '%env(sqlite_db_url:DATABASE_DIRECTORY)%'
    profiling_collect_backtrace: false
  orm:
    enable_native_lazy_objects: true
    validate_xml_mapping: true
    naming_strategy: Linkin\Component\DoctrineNamingStrategy\ORM\Mapping\CamelCaseNamingStrategy
    identity_generation_preferences:
      Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
    auto_mapping: true
    mappings:
      App:
        type: attribute
        is_bundle: false
        dir: '%kernel.project_dir%/src'
        prefix: 'App'
        alias: App
      Money\Money:
        type: xml
        dir: "%kernel.project_dir%/config/packages/doctrine"
        prefix: Money
        is_bundle: false
    controller_resolver:
      auto_mapping: false

when@test:
  doctrine:
    dbal:
      # "TEST_TOKEN" is typically set by ParaTest for parallel test isolation
      url: 'sqlite:///%kernel.project_dir%/tests/dreeve%env(default::TEST_TOKEN)%.db'
