doctrine_migrations:
    services:
        Doctrine\Migrations\Version\MigrationFactory: 'App\Infrastructure\Doctrine\Migrations\Factory\CommandBusAwareMigrationFactory'
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        'DoctrineMigrations': '%kernel.project_dir%/migrations'
    storage:
        table_storage:
            table_name: 'migration_versions'
    enable_profiler: false