# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    session: true
    assets:
        version_strategy: 'App\Infrastructure\Twig\UuidAssetVersioningStrategy'

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
