name: Feature request
description: Suggest an idea or improvement for this project
labels: ["new feature"]
assignees:
  - robiningelbrecht
body:
  - type: textarea
    id: the-feature
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: the-solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true