general:
  app_url: 'http://192.168.8.134:8081/'
  profile_picture_url: 'https://dgalywyr863hv.cloudfront.net/pictures/athletes/43397685/12321199/5/large.jpg'
  appSubTitle: 'Hybrid Athlete'
appearance:
  locale: 'en_US'
  unit_system: 'imperial'
  time_format: 12
  date_format: 'MONTH-DAY-YEAR'
gear:
  customGear:
    enabled: false
    hashtagPrefix: 'sfs'
    customGears: []
zwift:
  level: null
  racing_score: null
integrations:
  notifications:
    services: []
  ai:
    enabled: false
    enableUI: false