enabled: true
hashtagPrefix: sfs
components:
  - tag: chain
    label: Some cool chain
    imgSrc: chain.png
    attachedTo:
      - g1233776
      - '10130856'
    maintenance:
      - tag: lubed
        label: Lube
        interval:
          value: 500
          unit: km
      - tag: replaced
        label: Replace
        interval:
          value: 1000
          unit: km
      - tag: cleaned
        label: Clean
        interval:
          value: 1000
          unit: km
  - tag: di-2
    label: DI2 Battery
    imgSrc: battery.png
    attachedTo:
      - g1233776
      - g10130856
    maintenance:
      - tag: charged
        label: Charge
        interval:
          value: 11
          unit: hours
gears:
  - gearId: g10130856
    imgSrc: bike.webp
