name: Post release
on:
  workflow_dispatch:

jobs:
  changelog:
    name: Update changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: rhysd/changelog-from-release/action@v3
        with:
          file: CHANGELOG.md
          pull_request: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_summary_template: 'update changelog for %s changes'